### ISSUE TITLE
[Source Request] MangaInUa

### ISSUE THREAD

**Issue by Dippere** [nv95/kotatsu-parsers#14]
### Source name

Manga.in.ua

### Source link

https://manga.in.ua/

### Language

Ukrainian

### Other details

I wrote a Ukrainian translation in Weblate for app and would like to see the source from there as well. I will look forward to :)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/nv95/kotatsu-parsers) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by ztimms73** [comment]
@Dippere The parser is already written and ready. Wait for the next app release

**Comment by Dippere** [comment]
@ztimms73 thank you🌚
